FROM bellsoft/liberica-openjdk-alpine:11
COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d ./out ./src/org/example/generating_patterns/abstractFabicMethd/*.java
CMD java -classpath ./out org.example.generating_patterns.abstractFabicMethd.WebsiteAuctionProject